//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class GameProperties
{
    private static GameProperties instance = new GameProperties ();
    public static GameProperties Inst
    {
        get
        {
            return instance;
        }
    }

    public bool Chaser = false;
    public bool Chasee = false;
}

